language: node_js
node_js:
  - lts/*
after_success:
  - openssl aes-256-cbc -K $encrypted_356421c3f1d1_key -iv $encrypted_356421c3f1d1_iv
    -in deploy_key.enc -out ./deploy_key -d
deploy:
  provider: script
  script: script/deploy.sh
  on:
    branch: master
