language: node_js
node_js:
  - lts/*
after_success:
  - openssl aes-256-cbc -K $encrypted_356421c3f1d1_key -iv $encrypted_356421c3f1d1_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host ssh.acite.net\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
  - ssh -i ./deploy_key farislr@ssh.acite.net pwd
deploy:
  provider: script
  script: deploy_production.sh
  on:
    branch: master
